# Generated by Django 2.0.9 on 2026-05-06 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FarmerHub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargorating',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='cargorating',
            name='buyer',
        ),
        migrations.DeleteModel(
            name='CargoRating',
        ),
    ]
